Make `test_distributed_spawn.py` tell you how to run it correctly
Sample output if incorrect/missing args are specified:

```
RuntimeError: Missing expected env vars for `test_distributed_spawn.py`.  Please
ensure to specify the following:
'BACKEND' = one of ('gloo', 'nccl', 'ucc')
'WORLD_SIZE' = int >= 2
'TEMP_DIR' specifying a directory containing a barrier file named
'barrier'.

e.g.
touch /tmp/barrier && TEMP_DIR=/tmp BACKEND='nccl' WORLD_SIZE=2 python
/data/users/whc/pytorch/test/distributed/test_distributed_spawn.py
```

ghstack-source-id: 53bbe575fa1570aed8fd4d1768b6591971538757
Pull Request resolved: https://github.com/pytorch/pytorch/pull/112924